name: dart_utils
description: Dart utils by Miguel Angel Besalduch Garcia
version: 1.1.0
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  
dependencies:
  protobuf: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0