name: dart_utils
description: Dart utils by Miguel Angel Besalduch Garcia
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  protobuf: ^2.0.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0