name: dart_utils
description: Dart utils by Miguel Angel Besalduch Garcia
version: 2.1.3
homepage:

environment:
  sdk: ^3.9.0
  
dependencies:
  protobuf: ^5.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mock_http:
    git:
      url: https://github.com/dumabg/mock_http.git
