name: dart_utils
description: Dart utils by Miguel Angel Besalduch Garcia
version: 1.4.1
homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  
dependencies:
  protobuf: ^3.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mock_http:
    git:
      url: https://github.com/dumabg/mock_http.git
