name: dart_utils
description: Dart utils by Miguel Angel Besalduch Garcia
version: 1.2.1
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  protobuf: ^3.0.0
  http: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0